export default [
  {
    buttons: "1 x Up",
    taps: "1",
    paddle_id: "up",
    id: "2",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 1 Pushed",
  },
  {
    buttons: "1 x Down",
    taps: "1",
    paddle_id: "down",
    id: "1",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 1 Held",
  },
  {
    buttons: "2 x Up",
    taps: "2",
    paddle_id: "up",
    id: "2",
    data: "7860",
    scene_value_label: "Pressed 2 Times",
    button: "Button 2 Pushed",
  },
  {
    buttons: "2 x Down",
    taps: "2",
    paddle_id: "down",
    id: "1",
    data: "7860",
    scene_value_label: "Pressed 2 Times",
    button: "Button 2 Held",
  },
  {
    buttons: "3 x Up",
    taps: "3",
    paddle_id: "up",
    id: "2",
    data: "7920",
    scene_value_label: "Pressed 3 Times",
    button: "Button 3 Push",
  },
  {
    buttons: "3 x Down",
    taps: "3",
    paddle_id: "down",
    id: "1",
    data: "7920",
    scene_value_label: "Pressed 3 Times",
    button: "Button 3 Held",
  },
  {
    buttons: "4 x Up",
    taps: "4",
    paddle_id: "up",
    id: "2",
    data: "7980",
    scene_value_label: "Pressed 4 Times",
    button: "Button 4 Pushed",
  },
  {
    buttons: "4 x Down",
    taps: "4",
    paddle_id: "down",
    id: "1",
    data: "7980",
    scene_value_label: "Pressed 4 Times",
    button: "Button 4 Held",
  },
  {
    buttons: "5 x Up",
    taps: "5",
    paddle_id: "up",
    id: "2",
    data: "8040",
    scene_value_label: "Pressed 5 Times",
    button: "Button 5 Pushed",
  },
  {
    buttons: "5 x Down",
    taps: "5",
    paddle_id: "down",
    id: "1",
    data: "8040",
    scene_value_label: "Pressed 5 Times",
    button: "Button 5 Held",
  },
  {
    buttons: "1 x Config",
    taps: "1",
    paddle_id: "config",
    id: "3",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 7 Pushed",
  },
  {
    buttons: "Hold Up",
    taps: "0",
    paddle_id: "up",
    id: "2",
    data: "7800",
    scene_value_label: "Key Held down",
    button: "Button 6 Pushed",
  },
  {
    buttons: "Release Up",
    taps: "-1",
    paddle_id: "up",
    id: "2",
    data: "7740",
    scene_value_label: "Key Released",
    button: "N/A",
  },
  {
    buttons: "Hold Down",
    taps: "0",
    paddle_id: "down",
    id: "1",
    data: "7800",
    scene_value_label: "Key Held down",
    button: "Button 6 Held",
  },
  {
    buttons: "Release Down",
    taps: "-1",
    paddle_id: "down",
    id: "1",
    data: "7740",
    scene_value_label: "Key Released",
    button: "N/A",
  },
];
