export default [
  {
    buttons: "1 x Light",
    taps: "1",
    paddle_id: "light",
    id: "2",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 1 Pushed",
  },
  {
    buttons: "2 x Light",
    taps: "2",
    paddle_id: "light",
    id: "2",
    data: "7860",
    scene_value_label: "Pressed 2 Times",
    button: "Button 2 Pushed",
  },
  {
    buttons: "3 x Light",
    taps: "3",
    paddle_id: "light",
    id: "2",
    data: "7920",
    scene_value_label: "Pressed 3 Times",
    button: "Button 3 Pushed",
  },
  {
    buttons: "4 x Light",
    taps: "4",
    paddle_id: "light",
    id: "2",
    data: "7980",
    scene_value_label: "Pressed 4 Times",
    button: "Button 4 Pushed",
  },
  {
    buttons: "5 x Light",
    taps: "5",
    paddle_id: "light",
    id: "2",
    data: "8040",
    scene_value_label: "Pressed 5 Times",
    button: "Button 5 Pushed",
  },
  {
    buttons: "Light Hold",
    taps: "-1",
    paddle_id: "light",
    id: "2",
    data: "7800",
    scene_value_label: "Key Held down",
    button: "Button 8 Pushed",
  },
  {
    buttons: "Light Release",
    taps: "-1",
    paddle_id: "light",
    id: "2",
    data: "7740",
    scene_value_label: "Key Released",
    button: "Button 6 Pushed",
  },
  {
    buttons: "1 x Fan",
    taps: "1",
    paddle_id: "fan",
    id: "1",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 1 Held",
  },
  {
    buttons: "2 x Fan",
    taps: "2",
    paddle_id: "fan",
    id: "1",
    data: "7860",
    scene_value_label: "Pressed 2 Times",
    button: "Button 2 Held",
  },
  {
    buttons: "3 x Fan",
    taps: "3",
    paddle_id: "fan",
    id: "1",
    data: "7920",
    scene_value_label: "Pressed 3 Times",
    button: "Button 3 Held",
  },
  {
    buttons: "4 x Fan",
    taps: "4",
    paddle_id: "fan",
    id: "1",
    data: "7980",
    scene_value_label: "Pressed 4 Times",
    button: "Button 4 Held",
  },
  {
    buttons: "5 x Fan",
    taps: "5",
    paddle_id: "fan",
    id: "1",
    data: "8040",
    scene_value_label: "Pressed 5 Times",
    button: "Button 5 Held",
  },
  {
    buttons: "Fan Hold",
    taps: "-1",
    paddle_id: "fan",
    id: "1",
    data: "7800",
    scene_value_label: "Key Held down",
    button: "Button 8 Held",
  },
  {
    buttons: "Fan Release",
    taps: "-1",
    paddle_id: "fan",
    id: "1",
    data: "7740",
    scene_value_label: "Key Released",
    button: "Button 6 Held",
  },
  {
    buttons: "Light Rocker Up",
    taps: "1",
    paddle_id: "light_rocker_up",
    id: "3",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 7 Pushed",
  },
  {
    buttons: "Light Rocker Down",
    taps: "1",
    paddle_id: "light_rocker_down",
    id: "4",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 7 Held",
  },
  {
    buttons: "Fan Rocker Up",
    taps: "1",
    paddle_id: "fan_rocker_up",
    id: "5",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 9 Pushed",
  },
  {
    buttons: "Fan Rocker Down",
    taps: "1",
    paddle_id: "fan_rocker_down",
    id: "6",
    data: "7680",
    scene_value_label: "Pressed 1 Time",
    button: "Button 9 Held",
  },
];
